### ISSUE TITLE
All According to Keikaku

### ISSUE THREAD

**Issue by MaulingMonkey** [MaulingMonkey/thindx#1]
## Soundness Auditing
* [ ] Test out-of-bounds indicies
* [ ] Test invalid params
* [ ] Fuzz test everything
* [ ] OOM test coverage?
* [ ] Test refcount overflow behavior?
* [ ] Test against all variations of the DLL I can get my grubby hands on

## Documentation
* [ ] Verify examples for all APIs
* [x] 911492c7f3eaaa3ac95567ee3b550e749c742f47 Verify new style error docs for all APIs
* [x] 55ececff9581a7739045303107de17777019345c Verify all documentation refers to crate types where possible/sane
* [x] Verify all types listed in ~~crate level preamble~~ **mod _headers;**
* [x] 475619b97663043dc5f7f91734cc10fa7c52b199 Consistent doc comments order
* [x] ~~Finalize note CSS styling (quote or div, not both, also padding?)~~ **mooted:** docs.rs doesn't like stylin'~
* [x] a138976b190b3bf5aa062232e713fcb9d9855416 d53374a4d524692a083fd28dae3ff860cbd7af4a Ensure argument docs match actual arguments
* [x] Ensure Ok return docs match actual returns (911492c7f3eaaa3ac95567ee3b550e749c742f47 eliminated said docs)
* [ ] Document tested d3dcompiler version in soundness preamble
* [x] ~~Make version annotations consistent and useful~~ **Removed instead**
* [ ] Document all flags

## Refactoring
* [x] 9550ffaf3762a32a801bb999f8ffb890b0902c2c Deal with `D3D11::*` and `E::*` constants conflicting due to being the same type
* [x] 7d9e60ce7803a11be60b5b894a11a2be8ec92fce  Make trusting random shader blobs unsafe
* [x] 3f6e9da Maybe rename crate?  But maybe not.
* [x] ~~Spin out common crate for other thin* crates?~~ **To be done on an as needed basis, not up-front.**
* [x] 41841efbd98c15b7fe147d36c498163b472f7174 Reorganize files by category
* [x] bac08740a8b6ae415ceb7a3dcdcda142aaa4e8fa Fix symbol loading table alignment
* [x] f772785260c331f8e2804ad7cc8db49feb4d52b4 Write and leverage ~~winstr~~ `IntoAs*` traits
* [x] Add non-raw versions of `*_raw()` desc getters
* [x] e4fff50c4addbd7431fe41446b9b2b2b7b2c54b1 Consistent naming of `r#type` / `type_`

## Track Missing APIs
Now tracked via <https://docs.rs/thindx/*/thindx/_headers/> + `// TODO: ...`s
* [x] ~~#2 Lacking D3D10 effects support~~
* [x] ~~#3 Lacking undocumented API support~~
* [x] ~~#4 Lacking legacy API support~~
* [x] ~~#5 Lacking D3DDecompressShaders variations~~
* [x] ~~#6 Lacking d3d11shadertracing.h support~~
